name: CI
on:
  push:
    branches:
      - main
      - "renovate/**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version-file: .nvmrc
      - uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/.nvmrc') }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm ci
      - run: npm run lint -s
      - run: npm run dist -s
      - run: npm run report:size
      - run: npm run report:package
      - run: npm run test:coverage -s --json --runInBand
      # - run: npm run test:integration -s
      - run: npm run test:performance -s
      - run: base64 < ./tests/integration/__image_snapshots__/__diff_output__/* || true
      - run: npx danger ci --verbose
        if: ${{ github.event_name == 'pull_request' }}
        env:
          DANGER_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: mv coverage/lcov-report build || true
      - uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v2
        with:
          name: reports
          path: public
          retention-days: 1
